apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-testing
  annotations:
    github.com/project-slug: Harshitderepu/api-testing
spec:
  type: other
  lifecycle: unknown
  owner: Harshit
